// TẤT CẢ câu TTS / label tiếng Việt — không hard-code trong component.

// Chính sách bảo mật tách từng ý: màn hình hiển thị dạng danh sách, TTS đọc bản ghép (luôn khớp nhau).
// Thời hạn lưu trữ lấy từ BusinessRules.cs của backend.
const privacyIntro = 'VisionAid cần sự đồng ý của bạn trước khi sử dụng.';
const privacyPoints = {
  location:
    'Vị trí GPS được chia sẻ với người chăm sóc và dùng để báo khi bạn đến nơi quen thuộc. Lịch sử vị trí lưu 30 ngày.',
  camera: 'Camera phát hiện vật cản ngay trên điện thoại, không gửi hình ảnh lên máy chủ.',
  ocr: 'Ảnh chụp khi đọc chữ được lưu 90 ngày.',
  face: 'Nhận diện người quen dùng ảnh do người chăm sóc đăng ký. Ảnh bạn chụp để nhận diện bị xóa ngay sau khi xử lý.',
  fall: 'Khi phát hiện té ngã, ảnh chụp nhanh được gửi cho người chăm sóc và lưu 12 tháng.',
  rights: 'Bạn có thể yêu cầu người chăm sóc hoặc trung tâm xóa dữ liệu bất cứ lúc nào.',
} as const;

export const Strings = {
  app: {
    name: 'VisionAid',
    tagline: 'Trợ lý dẫn đường cho người khiếm thị',
    ready: 'VisionAid đã sẵn sàng. Bạn muốn làm gì?',
    loading: 'Đang tải',
  },
  auth: {
    loginTitle: 'Đăng nhập',
    emailLabel: 'Email',
    passwordLabel: 'Mật khẩu',
    loginButton: 'Đăng nhập',
    loginHint: 'Chạm hai lần để đăng nhập',
    emailHint: 'Nhập email đăng nhập',
    passwordHint: 'Nhập mật khẩu',
    loggingIn: 'Đang đăng nhập',
    loginSuccess: 'Đăng nhập thành công',
    invalidEmail: 'Email không hợp lệ',
    passwordRequired: 'Vui lòng nhập mật khẩu',
    wrongCredentials: 'Email hoặc mật khẩu không đúng',
    accountLocked: 'Tài khoản đã bị khóa. Vui lòng liên hệ người chăm sóc.',
    tooManyAttempts: 'Bạn thử quá nhiều lần, vui lòng đợi một phút',
    wrongRole:
      'Tài khoản này không dùng được trên ứng dụng di động. Vui lòng dùng trang web quản lý.',
    sessionExpired: 'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.',
    logoutButton: 'Đăng xuất',
    logoutHint: 'Chạm hai lần để đăng xuất khỏi ứng dụng',
    loggedOut: 'Đã đăng xuất',
    showPassword: 'Hiện mật khẩu',
    hidePassword: 'Ẩn mật khẩu',
    togglePasswordHint: 'Chạm hai lần để đổi chế độ hiện mật khẩu',
  },
  privacy: {
    title: 'Chính sách bảo mật',
    intro: privacyIntro,
    points: privacyPoints,
    content: [privacyIntro, ...Object.values(privacyPoints)].join(' '),
    readAgainButton: 'Nghe lại chính sách',
    readAgainHint: 'Chạm hai lần để nghe lại nội dung chính sách',
    acceptButton: 'Tôi đồng ý',
    acceptHint: 'Chạm hai lần để đồng ý chính sách bảo mật và tiếp tục',
    accepted: 'Đã ghi nhận sự đồng ý của bạn',
  },
  common: {
    back: 'Quay lại',
    backHint: 'Chạm hai lần để quay lại màn hình trước',
  },
  network: {
    online: 'Đang có kết nối mạng',
    offline: 'Không có mạng. Dẫn đường vẫn hoạt động; đọc chữ và nhận diện người quen tạm dừng.',
  },
  settings: {
    account: 'Tài khoản',
    phone: (phone: string) => `Số điện thoại ${phone}`,
    // Tốc độ / âm lượng giọng đọc (FE-02)
    speedTitle: 'Tốc độ đọc',
    speedValue: (rate: number) => `${rate.toLocaleString('vi-VN')} lần`,
    slower: 'Đọc chậm hơn',
    faster: 'Đọc nhanh hơn',
    speedHint: 'Chạm hai lần để đổi tốc độ đọc',
    speedChanged: (rate: number) => `Tốc độ đọc ${rate.toLocaleString('vi-VN')} lần`,
    atLimit: 'Đã ở mức giới hạn',
    volumeTitle: 'Âm lượng giọng đọc',
    volumeValue: (v: number) => `${Math.round(v * 100)} phần trăm`,
    quieter: 'Đọc nhỏ hơn',
    louder: 'Đọc to hơn',
    volumeHint: 'Chạm hai lần để đổi âm lượng giọng đọc',
    volumeChanged: (v: number) => `Âm lượng giọng đọc ${Math.round(v * 100)} phần trăm`,
    // Chế độ cảnh báo vật cản (FE-11)
    modeTitle: 'Chế độ cảnh báo',
    modeFull: 'Đầy đủ',
    modeFullHint: 'Báo mọi vật cản',
    modeMinimal: 'Tối giản',
    modeMinimalHint: 'Chỉ báo vật nguy hiểm như xe cộ, bậc thang',
    modeSelected: 'Đang chọn',
    batterySaverNote:
      'Pin yếu nên đang tạm dùng chế độ Tối giản. Chọn lại chế độ để bỏ, hoặc sạc pin.',
    savedLocal: 'Đã lưu trên máy, sẽ đồng bộ khi có mạng',
    changePassword: 'Đổi mật khẩu',
    changePasswordHint: 'Chạm hai lần để mở màn đổi mật khẩu',
  },
  password: {
    title: 'Đổi mật khẩu',
    currentLabel: 'Mật khẩu hiện tại',
    currentHint: 'Nhập mật khẩu đang dùng',
    newLabel: 'Mật khẩu mới',
    newHint: 'Ít nhất 8 ký tự, có chữ hoa, chữ thường, chữ số và ký tự đặc biệt',
    confirmLabel: 'Nhập lại mật khẩu mới',
    confirmHint: 'Nhập lại đúng mật khẩu mới',
    submit: 'Đổi mật khẩu',
    submitting: 'Đang đổi mật khẩu',
    submitHint: 'Chạm hai lần để đổi mật khẩu',
    empty: 'Vui lòng nhập đủ ba ô mật khẩu',
    tooShort: 'Mật khẩu mới phải có ít nhất 8 ký tự',
    tooLong: 'Mật khẩu mới không được quá 100 ký tự',
    weak: 'Mật khẩu mới cần có chữ hoa, chữ thường, chữ số và ký tự đặc biệt',
    same: 'Mật khẩu mới phải khác mật khẩu hiện tại',
    mismatch: 'Hai lần nhập mật khẩu mới không giống nhau',
    wrongCurrent: 'Mật khẩu hiện tại không đúng',
    changed: 'Đã đổi mật khẩu. Vui lòng đăng nhập lại bằng mật khẩu mới',
  },
  screens: {
    ocr: 'Đọc chữ và mã QR',
    face: 'Nhận diện người quen',
    location: 'Tôi đang ở đâu',
    emergency: 'Khẩn cấp',
    settings: 'Cài đặt',
  },
  home: {
    title: 'Màn hình chính',
    greeting: (name: string) => (name ? `Xin chào, ${name}` : 'Xin chào'),
    startNavigation: 'Bắt đầu dẫn đường',
    startNavigationHint: 'Chạm hai lần để bắt đầu phát hiện vật cản',
    settingsHint: 'Chạm hai lần để mở cài đặt và đăng xuất',
  },
  navigation: {
    started: 'Bắt đầu dẫn đường. Hãy giữ điện thoại hướng về phía trước.',
    stopped: 'Đã dừng dẫn đường',
    stop: 'Dừng dẫn đường',
    stopHint: 'Chạm hai lần để dừng phát hiện vật cản',
    active: 'Đang dẫn đường',
    clear: 'Chưa phát hiện vật cản',
    cameraExplain:
      'Để phát hiện vật cản, VisionAid cần dùng camera. Hình ảnh chỉ được xử lý trên điện thoại.',
    cameraDenied:
      'Chưa có quyền camera nên không thể dẫn đường. Đang mở cài đặt, hãy bật quyền Camera cho VisionAid.',
    cameraUnavailable: 'Không mở được camera',
    modelLoading: 'Đang chuẩn bị nhận diện vật cản',
    modelFailed: 'Không khởi động được nhận diện vật cản',
    paused: 'Ứng dụng đã chạy nền, tạm dừng cảnh báo vật cản. Mở lại VisionAid để tiếp tục.',
    resumed: 'Tiếp tục dẫn đường',
    pausedOtherScreen: 'Tạm dừng cảnh báo vật cản',
    resumedHome: 'Tiếp tục cảnh báo vật cản',
    cameraStalled:
      'Camera không hoạt động, cảnh báo vật cản đang tạm dừng. Hãy dừng lại và dùng gậy. Thử dừng rồi bắt đầu dẫn đường lại.',
    cameraRecovered: 'Camera đã hoạt động lại, tiếp tục cảnh báo vật cản',
  },
  license: {
    blocked:
      'Gói dịch vụ của bạn chưa có hoặc đã hết hạn nên một số tính năng bị tạm dừng. Vui lòng liên hệ người chăm sóc để gia hạn. Bạn vẫn có thể gọi khẩn cấp.',
    expiring: (days: number) =>
      days <= 0
        ? 'Gói dịch vụ đã hết hạn. Vui lòng liên hệ người chăm sóc để gia hạn.'
        : `Gói dịch vụ sẽ hết hạn sau ${days} ngày. Vui lòng liên hệ người chăm sóc để gia hạn.`,
    trial: (days: number) =>
      days <= 0 ? 'Hôm nay là ngày dùng thử cuối cùng.' : `Bạn đang dùng thử, còn ${days} ngày.`,
    navigationBlocked:
      'Chưa có gói dịch vụ nên chưa dùng được dẫn đường. Vui lòng nhờ người chăm sóc đăng ký gói. Bạn vẫn có thể gọi khẩn cấp.',
  },
  qr: {
    title: 'Quét mã QR',
    openScanner: 'Quét mã QR',
    openScannerHint: 'Chạm hai lần rồi hướng camera sau vào mã QR',
    aim: 'Hướng camera sau vào mã QR. Điện thoại sẽ rung khi đọc được mã.',
    url: (domain: string) => `Mã QR chứa đường dẫn tới trang ${domain}.`,
    askOpen: (domain: string) => `Bạn có muốn mở trang ${domain} không? Nói đồng ý để mở.`,
    notOpened: 'Không mở đường dẫn',
    phone: (digits: string) => `Mã QR chứa số điện thoại ${digits}`,
    email: (address: string) => `Mã QR chứa địa chỉ thư điện tử ${address}`,
    wifi: (ssid: string) => `Mã QR chứa thông tin mạng Wi-Fi ${ssid}`,
    text: (content: string) => `Nội dung mã QR: ${content}`,
    truncated: '. Nội dung còn dài, đã đọc phần đầu.',
    openLink: 'Mở trang',
    openLinkHint: 'Chạm hai lần để mở đường dẫn trong mã QR bằng trình duyệt',
    scanAgain: 'Quét mã khác',
    scanAgainHint: 'Chạm hai lần để quét một mã QR khác',
  },
  fall: {
    detected: 'Phát hiện té ngã. Nói tôi ổn, hoặc chạm vào màn hình để hủy cảnh báo.',
    detectedScreenReader:
      'Phát hiện té ngã. Nói tôi ổn, hoặc chạm hai lần vào màn hình để hủy cảnh báo.',
    cancelled: 'Đã hủy cảnh báo',
    alreadySent: 'Cảnh báo đã được gửi đến người chăm sóc',
    cancelUncertain:
      'Mất mạng nên chưa chắc đã hủy kịp. Cảnh báo có thể đã được gửi đến người chăm sóc.',
    sent: 'Đã gửi cảnh báo đến người chăm sóc',
    queued: 'Chưa gửi được cảnh báo lên máy chủ, ứng dụng sẽ tự gửi lại.',
    overlayLabel: 'Hủy cảnh báo té ngã',
    overlayHint: 'Chạm hai lần để hủy cảnh báo té ngã',
    countdown: (seconds: number) => `Tự gửi cảnh báo sau ${seconds} giây`,
    noAlert: 'Không có cảnh báo té ngã nào để hủy',
  },
  battery: {
    low: 'Pin yếu, đã chuyển sang chế độ tiết kiệm, chỉ báo vật nguy hiểm.',
  },
  emergency: {
    title: 'Khẩn cấp',
    open: 'Gọi khẩn cấp',
    openHint: 'Chạm hai lần để gửi cảnh báo khẩn cấp cho người chăm sóc và gọi người thân',
    intro: 'Màn hình khẩn cấp. Chạm nút lớn để gửi cảnh báo và gọi người thân.',
    confirm: 'Xác nhận gửi',
    confirmHint: 'Chạm hai lần để gửi cảnh báo khẩn cấp ngay',
    cancel: 'Hủy',
    cancelHint: 'Chạm hai lần để không gửi cảnh báo',
    sending: 'Đang gửi cảnh báo khẩn cấp',
    sent: 'Đã gửi cảnh báo khẩn cấp đến người chăm sóc.',
    queued: 'Chưa gửi được cảnh báo lên máy chủ, ứng dụng sẽ tự gửi lại.',
    calling: (name: string) => `Đang gọi ${name}.`,
    dialing: (name: string, number: string) =>
      `Đã mở sẵn số ${number} của ${name}. Hãy chạm nút gọi màu xanh ở giữa, phía dưới màn hình.`,
    zalo: (name: string) => `Đang mở Zalo để liên lạc ${name}.`,
    noContact: 'Chưa có số liên lạc khẩn cấp. Hãy nhờ người chăm sóc thêm số trên trang quản lý.',
    callPermissionExplain: 'Để tự gọi cho người thân khi khẩn cấp, VisionAid cần quyền gọi điện.',
    again: 'Gửi cảnh báo lần nữa',
    againHint: 'Chạm hai lần để gửi thêm một cảnh báo khẩn cấp',
  },
  location: {
    title: 'Tôi đang ở đâu',
    open: 'Tôi đang ở đâu',
    openHint: 'Chạm hai lần để nghe vị trí hiện tại của bạn',
    locating: 'Đang xác định vị trí',
    here: (address: string) => `Bạn đang ở ${address}`,
    cached: (time: string, day: number, month: number, address: string) =>
      `Vị trí gần nhất được ghi nhận lúc ${time}, ngày ${day} tháng ${month}: ${address}. Thông tin này có thể không còn chính xác.`,
    none: 'Chưa có thông tin vị trí đã lưu',
    arrived: (place: string, message: string | null) =>
      message ? `Bạn đã đến ${place}. ${message}` : `Bạn đã đến ${place}`,
    trackingTitle: 'VisionAid đang chia sẻ vị trí',
    trackingBody: 'Người chăm sóc có thể biết bạn đang ở đâu.',
    again: 'Hỏi lại vị trí',
    againHint: 'Chạm hai lần để xác định lại vị trí hiện tại',
    permissionExplain:
      'Để cho bạn biết mình đang ở đâu và chia sẻ vị trí với người chăm sóc, VisionAid cần quyền vị trí.',
    servicesOff:
      'Định vị trên điện thoại đang tắt. Người chăm sóc sẽ không thấy vị trí của bạn. Hãy bật Vị trí trong cài đặt nhanh.',
    permissionDenied:
      'Chưa có quyền vị trí nên chỉ đọc được vị trí đã lưu. Đang mở cài đặt, hãy bật quyền Vị trí cho VisionAid.',
  },
  ocr: {
    title: 'Đọc chữ',
    open: 'Đọc chữ',
    openHint: 'Chạm hai lần rồi hướng camera sau vào chữ cần đọc',
    aim: 'Hướng camera sau vào chữ cần đọc, cách khoảng một gang tay, rồi chạm nút chụp ở cuối màn hình.',
    capture: 'Chụp và đọc',
    captureHint: 'Chạm hai lần để chụp ảnh và đọc chữ trong ảnh',
    reading: 'Đang đọc',
    offline: 'Không có mạng, đang đọc chữ bằng chế độ ngoại tuyến',
    notClear: 'Không đọc rõ, vui lòng chụp lại ở nơi đủ sáng',
    again: 'Chụp lại',
    againHint: 'Chạm hai lần để chụp và đọc lại',
  },
  face: {
    title: 'Nhận diện người quen',
    open: 'Nhận diện người quen',
    openHint: 'Chạm hai lần rồi hướng camera sau vào khuôn mặt người đối diện',
    aim: 'Hướng camera sau vào khuôn mặt người đối diện, cách khoảng một sải tay, rồi chạm nút chụp ở cuối màn hình.',
    capture: 'Chụp và nhận diện',
    captureHint: 'Chạm hai lần để chụp ảnh và nhận diện người quen',
    identifying: 'Đang nhận diện',
    matched: (name: string, relationship: string | null) =>
      relationship ? `${name}, ${relationship}, ở phía trước` : `${name} ở phía trước`,
    notMatched: 'Không nhận ra người này',
    lowConfidence: 'Chưa rõ, vui lòng hướng camera thẳng vào khuôn mặt',
    retake: 'Chưa nhận diện được. Hãy đưa camera lại gần khuôn mặt, ở nơi đủ sáng, rồi chụp lại.',
    unavailable: 'Tính năng nhận diện người quen tạm thời không khả dụng',
    again: 'Nhận diện người khác',
    againHint: 'Chạm hai lần để quay lại camera và chụp người khác',
  },
  voice: {
    button: 'Ra lệnh giọng nói',
    buttonHint:
      'Chạm hai lần rồi nói một lệnh sau tiếng bíp, ví dụ: bắt đầu, đọc chữ, trợ giúp. Ở bất kỳ màn hình nào cũng có thể nhấn nút âm lượng để ra lệnh.',
    listening: 'Đang nghe…',
    confirming: 'Đang chờ bạn xác nhận',
    cancel: 'Hủy',
    cancelHint: 'Chạm hai lần để ngừng nghe',
    cancelled: 'Đã hủy lệnh giọng nói',
    micExplain: 'Để nhận lệnh giọng nói, VisionAid cần dùng micro.',
    micDenied:
      'Chưa có quyền micro nên không nhận được lệnh giọng nói. Đang mở cài đặt, hãy bật quyền Micro cho VisionAid.',
    notNavigating: 'Chưa bắt đầu dẫn đường',
    modeMinimal: 'Đã chuyển sang chế độ tối giản, chỉ báo vật nguy hiểm',
    modeFull: 'Đã chuyển sang chế độ đầy đủ',
    faster: 'Đã đọc nhanh hơn',
    slower: 'Đã đọc chậm hơn',
    fastest: 'Đã ở tốc độ đọc nhanh nhất',
    slowest: 'Đã ở tốc độ đọc chậm nhất',
    louder: 'Đã tăng âm lượng',
    quieter: 'Đã giảm âm lượng',
    loudest: 'Đã ở mức âm lượng lớn nhất',
    quietest: 'Đã ở mức âm lượng nhỏ nhất',
    nothingToRepeat: 'Chưa có thông báo nào để đọc lại',
    help: (commands: string) => `Bạn có thể nói: ${commands}.`,
    notUnderstood: 'Tôi chưa hiểu, vui lòng nói lại',
    wakeHint:
      'Khi cần ra lệnh, nhấn nút tăng hoặc giảm âm lượng. Muốn chỉnh âm lượng, hãy nói tăng âm lượng hoặc giảm âm lượng.',
    offlineEngine: 'Đang dùng nhận dạng giọng nói ngoại tuyến',
    retryOffline: 'Mạng không ổn định, đang dùng nhận dạng ngoại tuyến. Vui lòng nói lại.',
    offlineUnavailable:
      'Không có mạng nên chưa nhận được lệnh giọng nói trên máy này. Bạn hãy dùng các nút trên màn hình.',
    // "đồng ý" (2 âm tiết) thay vì "có": Google hay trả rỗng với từ 1 âm tiết. Vẫn nhận "có", "xác nhận".
    confirmEmergency: 'Bạn có chắc muốn gọi khẩn cấp? Nói đồng ý để xác nhận.',
    emergencyCancelled: 'Đã hủy gọi khẩn cấp',
  },
  errors: {
    forbidden: 'Bạn không có quyền thực hiện thao tác này',
    unavailable: 'Tính năng tạm thời không khả dụng',
    offline: 'Không có kết nối mạng. Vui lòng kiểm tra mạng và thử lại.',
    ocrNeedsNetwork: 'Tính năng đọc chữ cần kết nối mạng',
    faceNeedsNetwork: 'Tính năng nhận diện người quen cần kết nối mạng',
  },
  distance: {
    Near: 'ở gần',
    Medium: 'phía trước',
    Far: 'ở xa',
  },
  // Cuộc gọi video với người chăm sóc (WebRTC, §9.10) — VIU gửi camera sau + nghe tiếng
  call: {
    calling: 'Đang gọi người chăm sóc',
    incoming: (name: string | null) => `${name ?? 'Người chăm sóc'} đang gọi. Tự động nghe máy`,
    sosWaiting: 'Đang mở cuộc gọi video khẩn cấp với người chăm sóc',
    connecting: 'Đang kết nối cuộc gọi. Tạm dừng cảnh báo vật cản',
    connected:
      'Đã kết nối. Người chăm sóc đang xem camera của bạn. Bấm phím âm lượng để kết thúc cuộc gọi',
    ended: 'Đã kết thúc cuộc gọi',
    noAnswer: 'Người chăm sóc chưa nghe máy',
    rejected: 'Người chăm sóc đã từ chối cuộc gọi',
    lost: 'Mất kết nối cuộc gọi',
    failed: 'Không gọi được người chăm sóc. Vui lòng thử lại',
    busy: 'Đang có cuộc gọi',
    needsNetwork: 'Gọi người chăm sóc cần kết nối mạng',
    maxDuration: 'Cuộc gọi đã đạt thời lượng tối đa và được kết thúc',
    noCall: 'Không có cuộc gọi nào',
    resumed: 'Đã bật lại cảnh báo vật cản',
    overlayLabel: 'Đang trong cuộc gọi với người chăm sóc',
    endButton: 'Kết thúc cuộc gọi',
    endHint: 'Chạm hai lần để kết thúc cuộc gọi',
    phase: {
      outgoing: 'Đang gọi…',
      waiting: 'Đang chờ người chăm sóc nghe máy…',
      connecting: 'Đang kết nối…',
      connected: 'Đang trong cuộc gọi',
    },
  },
  // Hướng dẫn rẽ/tránh (Hybrid AI, §9.1) — cùng mẫu câu với TtsTemplateHelper.cs của backend
  guidance: {
    stop: 'Dừng lại, có vật cản phía trước',
    proceed: 'Đường thông thoáng, tiếp tục đi',
    turnLeft: (name: string | null, where: string | null) =>
      `Có ${name ?? 'vật cản'} phía ${where ?? 'trước'}, hãy bước sang trái`,
    turnRight: (name: string | null, where: string | null) =>
      `Có ${name ?? 'vật cản'} phía ${where ?? 'trước'}, hãy bước sang phải`,
    position: {
      LEFT: 'bên trái',
      CENTER_LEFT: 'trái trước',
      CENTER: 'trước',
      CENTER_RIGHT: 'phải trước',
      RIGHT: 'bên phải',
    },
  },
} as const;
